### PR TITLE
Workflow optimization and BS tunnel bug fix

### PR DESCRIPTION
**Pull request by shammowla**
1) Added a bash script that terminates idle browserstack sessions prior to running functional tests
2) Consolidated the unit test and functional tests jobs into one. Avoid installing and building Alloy twice. 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Improvement (non-breaking change which does not add functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html) or I'm an Adobe employee.
- [ ] I have made any necessary test changes and all tests pass.
- [ ] I have run the Sandbox successfully.

### CODE REVIEW

**Comment by shammowla** [comment]
The changes helped with the test run and avoided idling - https://github.com/adobe/alloy/actions/runs/622089452

**Comment by shammowla** [comment]
image

**Comment by shammowla** [comment]
Multiple test runs -
1) https://github.com/adobe/alloy/actions/runs/622178067
2) https://github.com/adobe/alloy/runs/2034505078?check_suite_focus=true (with serializer) 
3) https://github.com/adobe/alloy/runs/2034629284?check_suite_focus=true

**Review by jonsnyder — APPROVED** [review]

**Review by Aaronius — APPROVED** [review]
Thanks! I'm excited to see this working.

**Pull request merged**
