### PR TITLE
TNT-44322 Support Surfaces in interact requests

### PR DESCRIPTION
**Pull request by XDex**
## Description

Support Surfaces in personalization query requests
Note: PR set to draft until AJO backend is ready for e2e testing. Once it's ready, a functional e2e test will be added.

## Related Issue

https://jira.corp.adobe.com/browse/TNT-44322

## Motivation and Context

Support Surfaces in personalization query requests

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Improvement (non-breaking change which does not add functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html) or I'm an Adobe employee.
- [x] I have made any necessary test changes and all tests pass.
- [x] I have run the Sandbox successfully.

### CODE REVIEW

**Review by jonsnyder — COMMENTED** [review]
This looks good. Like you said a functional e2e test should be added.

**Review by carterworks — APPROVED** [review]

**Comment by ninaceban** [comment]
Is this PR still relevant? I see the same changes as in #864 . Thank you

**Comment by XDex** [comment]
@ninaceban Yes, #864 has the same mods, since it relies on the mods from this one being merged. I'll be rebasing it once this one gets merged (once we have the AJO backend up in prod and I'm able to add functional tests).

**Comment by XDex** [comment]
Closing this one, as #864 has these mods included and it's easier to review a single consolidated PR

**Pull request closed without merging**
