### PR TITLE
Polyfill for IE 11 

### PR DESCRIPTION
**Pull request by shammowla**
## Description
Promises in unit tests were failing on IE 11. 

## Motivation and Context
Added "@babel/polyfill" as dependency and imported into unit tests.

## How Has This Been Tested?
Ran cross browser unit tests on Saucelabs.

### CODE REVIEW

**Comment by Aaronius** [comment]
@shammowla Can you fill me in a little more on the strategy here? Why did you choose to use @babel/polyfill in one test and core-js/modules/es6.promise in another? Why did you decide to import the polyfill in each test instead of including a promise polyfill in the [karma file configuration](http://karma-runner.github.io/4.0/config/files.html)?

**Comment by shammowla** [comment]
@Aaronius In the last commit I was testing the commonjs vs the @babel/polyfill package. I added the @babel/polyfill to the Karma config. Should I make @babel/polyfill  a dev dependency?

**Comment by Aaronius** [comment]
Thanks @shammowla. This is better, but using @babel/polyfill poses a problem since it polyfills more than just `Promise`. We're trying to mimic a real customer's website as closely as possible when we test. In our user documentation, we will tell our customers that if they need to support Internet Explorer, they will need to have polyfilled `window.Promise`. We don't say they need to polyfill anything else though, and if they don't polyfill anything else, then we shouldn't polyfill anything else in our tests either.

For example, if our library tries to use `Set`, which is not supported in Internet Explorer, tests should fail, because Alloy will also likely fail in Internet Explorer on our customer's websites. By introducing `@babel/polyfill` into our tests through Karma, they won't fail (a bad thing), because `Set` will have been polyfilled.

Instead of `@babel/polyfill`, I recommend using the Promise polyfill from https://www.npmjs.com/package/promise-polyfill. I recommend installing it as a dev dependency.

**Comment by shammowla** [comment]
@Aaronius I switched to promise-polyfill. The "fireDestinations" spec is failing on IE11, but the other tests are looking good.

**Comment by Aaronius** [comment]
👍 That's good! We're catching bugs!

**Pull request merged**
