### PR TITLE
use debug_enabled query string parameter

### PR DESCRIPTION
**Pull request by jonsnyder**
Use debug_enabled query string parameter to turn debugging on or off.

## Related Issue

https://jira.corp.adobe.com/browse/CORE-28206

## Motivation and Context

Allow customers to turn on debugging without modifying the code of the website.

## How Has This Been Tested?

unit tests for the stringToBoolean util.  Manual sandbox testing to test the createInstance changes.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by Aaronius** [comment]
@jonsnyder I added a commit with a fix for the build issue.

**Comment by Aaronius** [comment]
BTW, I think this looks good. I wonder if we should call the parameter `alloy_debug_enabled` to distinguish it from other things that might use `debug_enabled`? I don't know......if you've considered it and decided against it then that's all good with me.

From the demo to the alpha customers, it sounds like we might be renaming "debug" to "log" or "logging" or something like that, so the query param may eventually change due to that as well FYI.

**Comment by jonsnyder** [comment]
The downside to using debug_enabled is it may conflict with a param that the customer is using internally.  This would clog up their logs with alloy logs.  You are right that `debug_enabled` should probably be changed to `log_enabled`.  Of course then we could support log levels with this parameter and call it `log_level`

1. `log_enabled` - may conflict with customer param
2. `alloy_log_enabled`
3. `[instanceVariableName]_log_enabled` - this would allow you to see just one instance's logging

@jfkhoury what do you think?

**Comment by jfkhoury** [comment]
@jonsnyder I would prefix it with ‘alloy’. ‘alloy_log’ or ‘alloy_log_enabled’

**Comment by jfkhoury** [comment]
@Aaronius @jonsnyder  I added a commit to rename `debug_enabled` to `alloy_log`.

**Pull request merged**
