### PR TITLE
TNT-43421 Fix circular dependency in Web SDK

### PR DESCRIPTION
**Pull request by XDex**
## Description

Fix circular dependency introduced after ShadowDOM implementation.

## Related Issue

https://jira.corp.adobe.com/browse/TNT-43421

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Improvement (non-breaking change which does not add functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html) or I'm an Adobe employee.
- [x] I have made any necessary test changes and all tests pass.
- [x] I have run the Sandbox successfully.

### CODE REVIEW

**Review by jfkhoury — APPROVED** [review]
I don't know if `beacon` is the best folder name here but I'll leave it to the team to decide ;)

**Comment by jonsnyder** [comment]
I don't understand where the circular dependency was and how this fixes it. Could you explain?

**Comment by XDex** [comment]
@jonsnyder Sure, as mentioned in linked ticket, Rollup reported this circular dependency:
```
(!) Circular dependency
[build] src/utils/index.js -> src/utils/fireReferrerHideableImage.js -> src/utils/dom/index.js -> src/utils/dom/awaitSelector.js -> src/utils/dom/selectNodes.js -> src/components/Personalization/dom-actions/dom/selectNodesWithShadow.js -> src/utils/index.js
```
So, when a package imports `src/utils/fireReferrerHideableImage.js` this is referenced from `src/utils/index.js`, meanwhile `fireReferrerHideableImage.js` has another reference to `src/utils/index.js` in its dependency graph, when `startsWith` util is imported from `src/utils/index.js` in `selectNodesWithShadow.js`, hence the circular dependency.
By moving `fireReferrerHideableImage.js` to a nested directory, like `src/utils/beacon` we're fixing it, since it's no longer imported from `src/utils/index.js`, and thus any utils from the root `src/utils/` can now be used in any of its dependencies.
Here's a [relevant blogpost](https://spin.atomicobject.com/2018/06/25/circular-dependencies-javascript/) on circular dependencies.

**Comment by jonsnyder** [comment]
Closing in favor of #795

**Pull request closed without merging**
