### PR TITLE
[CJM-48525]Renamed renderDecision command to evaluateRulesets

### PR DESCRIPTION
**Pull request by shandilya3**
## Description
Renamed renderDecision command to evaluateRulesets

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Improvement (non-breaking change which does not add functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html) or I'm an Adobe employee.
- [X] I have made any necessary test changes and all tests pass.
- [X] I have run the Sandbox successfully.

### CODE REVIEW

**Review by carterworks — CHANGES_REQUESTED** [review]
You've missed quite a few places and usages.

https://github.com/search?q=repo%3Aadobe%2Falloy%20renderDecisions&type=code

**Comment by shandilya3** [comment]
> You've missed quite a few places and usages.
> 
> https://github.com/search?q=repo%3Aadobe%2Falloy%20renderDecisions&type=code

@carterworks here we are only renaming command. 

In future, renderDecisions flag is going to be renamed to renderPropositions as I understand it.

**Comment by jasonwaters** [comment]
@shandilya3 you described this PR as renaming to `evaluateRulesets`, but in the code you renamed it to `executeRuleSets`.  

I think `evaluateRulesets` is correct.  Note the casing as well.  
@jonsnyder can you confirm this is the name you prefer? ⬆️

**Comment by jonsnyder** [comment]
Yes "evaluateRulesets"

**Review by jonsnyder — APPROVED** [review]

**Review by jasonwaters — APPROVED** [review]

**Pull request merged**
