### PR TITLE
Create CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by jfkhoury**
## Description

More to come, the first stab at a contribution model that applies to internal and external contributors.

## Motivation and Context

We need our contribution model to be crystal clear.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Improvement (non-breaking change which does not add functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html) or I'm an Adobe employee.
- [ ] I have made any necessary test changes and all tests pass.
- [ ] I have run the Sandbox successfully.

### CODE REVIEW

**Comment by carterworks** [comment]
Is there value in including instruction on our testing and code quality standards? 

It needs to:

- have functional (and maybe unit tests)
- have been tested on alloyio.com and maybe another page, and 
- (maybe) include a page on the sandbox or a demo in github.com/adobe/alloy-samples
- Pass formatting and usage standards (`npm run format` and `npm run lint`)

**Comment by jfkhoury** [comment]
> Is there value in including instruction on our testing and code quality standards?
> 
> It needs to:
> 
> * have functional (and maybe unit tests)
> * have been tested on alloyio.com and maybe another page, and
> * (maybe) include a page on the sandbox or a demo in github.com/adobe/alloy-samples
> * Pass formatting and usage standards (`npm run format` and `npm run lint`)

Yes, absolutely! Thank you for the suggestions, I will make the change.

**Review by jonsnyder — APPROVED** [review]
Love it!

**Comment by jfkhoury** [comment]
@carterworks It turned out I did mention the functional tests and sandbox. Can you re-review, please so I can merge this version? Thanks!

**Review by carterworks — APPROVED** [review]

**Pull request merged**
