### PR TITLE
Check only the error detail in IAB tests

### PR DESCRIPTION
**Pull request by raresvla**
## Description

The errors are now updated to contain a short `title` and then a `detail` field. One example:

```javascript
//before
{
  "type": "https://ns.adobe.com/aep/errors/EXEG-0103-400",
  "status": 400,
  "title": "Invalid request. No value supplied for required field consent.[0].value'.",
  "report": {
    "requestId": "0837dd9a-c070-4cdc-99ae-725b1671c3f0",
    "configId": "bc1a10e0-aee4-4e0e-ac5b-cdbb9abbec83:prod",
    "orgId": "5BFE274A5F6980A50A495C08@AdobeOrg"
  }
}
```
Is now changed to:

```javascript
//after
{
  "type": "https://ns.adobe.com/aep/errors/EXEG-0103-400",
  "status": 400,
  "title": "Invalid request",
  "detail": "No value supplied for required field consent.[0].value'.",
  "report": {
    "requestId": "0837dd9a-c070-4cdc-99ae-725b1671c3f0",
    "configId": "bc1a10e0-aee4-4e0e-ac5b-cdbb9abbec83:prod",
    "orgId": "5BFE274A5F6980A50A495C08@AdobeOrg"
  }
}
```

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Improvement (non-breaking change which does not add functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html) or I'm an Adobe employee.
- [x] I have made any necessary test changes and all tests pass.
- [x] I have run the Sandbox successfully.

### CODE REVIEW

**Review by shammowla — APPROVED** [review]

**Review by jonsnyder — APPROVED** [review]
Thanks for fixing these!

**Review by costimuraru — APPROVED** [review]

**Comment by costimuraru** [comment]
Can we merge this, so we can get the alloy e2e tests passing :) ? https://github.com/adobe/alloy/actions/workflows/pre-edge-deploy.yaml

**Review by flore77 — APPROVED** [review]

**Comment by Aaronius** [comment]
Hey, just a heads up for everyone. We're planning on starting to test prior versions of Alloy against Konductor. In other words, for previously released versions of Alloy, we want to run the tests contained in the version's git tag against the source in the version's git tag.  When we have assertions that test `title` values, like we do here, and Konductor changes these title values, this will cause tests in previously released versions' git tags to fail. This is problematic for our strategy of testing prior versions of Alloy.

We either need to use more generic tests (in which case Konductor will be responsible for testing `title` values in their own tests, which may already be happening) or we need Konductor to treat changes to `title` values as backward-incompatible.

**Comment by Aaronius** [comment]
@raresvla @costimuraru, it might help us to adjust our assertions appropriately if you can clearly outline how you treat backward compatibility respective to each field. For example, it seems changes to the value of `title` is considered backward-compatible, but what about `type` and `status`?

**Comment by raresvla** [comment]
@Aaronius, indeed, changes to `title` and `detail` could be possible. On the other hand:
* `type` contains the error URI, which is not expected to change (an error type could only be deprecated in the future)
* `status` contains the corresponding HTTP status code that best describes the error and its severity -- again, very unlikely to change, since we're mapping standard status codes anyways.

**Pull request merged**
