### PR TITLE
Add a test page with custom elements for TNT-42028 functional tests

### PR DESCRIPTION
**Pull request by XDex**
Add a test page with custom elements for TNT-42028 functional tests

## Description

Add a test page with custom elements for "TNT-42028 Shadow DOM support" functional tests.
We need to deploy this page to alloyio.com before #773 is merged in order to be able to create a functional test, as the existing `testPage.html` has no custom elements with Shadow DOM in it, thus we can't create a test activity in VEC.

## Related Issue

#773 

## Motivation and Context

Add a test page with custom elements to alloyio.com before #773 is merged in order to be able to create a functional test.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Improvement (non-breaking change which does not add functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html) or I'm an Adobe employee.
- [x] I have made any necessary test changes and all tests pass.
- [x] I have run the Sandbox successfully.

### CODE REVIEW

**Comment by XDex** [comment]
Could somebody please help with uploading to alloyio.com accorging to [these instructions](https://github.com/adobe/alloy/wiki/Accessing-and-uploading-sandbox-builds-to-Alloyio.com) after the PR is merged (as I don't have access to Azure)?

**Comment by shammowla** [comment]
@XDex , I can help you with hosting on alloyio.com. Let me know what needs to be hosted

**Comment by XDex** [comment]
@shammowla Thank you! I just need to update a test fixture in the sandbox, so I could create an activity in VEC for a functional test. Could you please approve the PR, merge it and deploy to alloyio.com?

**Comment by jonsnyder** [comment]
We've generally avoided creating custom html pages for tests. Is it possible to setup the page content using javascript inside of the test? This way you don't have to push code to alloyio.com before getting a test to work.

**Comment by XDex** [comment]
> We've generally avoided creating custom html pages for tests. Is it possible to setup the page content using javascript inside of the test? This way you don't have to push code to alloyio.com before getting a test to work.

@jonsnyder It's possible, but it that case I won't be able to create an activity testing Shadow Dom in VEC, as there won't be any custom elements on the page when it's opened in Target UI. I could, of course, manually add a Shadow DOM selector to the offer that gets delivered in the test, but this kind of defeats the purpose of an end-to-end test, where the offers get created in VEC on custom elements with shadow DOM and then delivered and applied by alloy.

**Comment by XDex** [comment]
@jonsnyder @shammowla So, would you be ok with approving and merging this PR?

**Comment by jonsnyder** [comment]
I'm okay with adding a test page to alloyio.com to manually test things in Target VEC. That's what we have the sandbox for, so we can do manual testing. What we are talking about here is to add a functional test that creates shadow Dom elements that get selected from the test.  Perhaps I'm missing something. It may be useful to have a 30 minute meeting to understand this feature better. @jfkhoury can you put together a meeting for this?

**Comment by ninaceban** [comment]
It is challenging to add a functional test because the way Target works, you must have a page first, so you could add an activity using VEC. Which basically is not the case when it comes to automated functional tests. I had the same challenge when I have added the other functional test related to auto rendering and especially SPA. But there is a solution/workaround.

I would recommend: 
1. Create a sample HTML page with a simple Custom Element and run it on `localhost` using `http-server` or any other server
2. Load the page in VEC and create the activity
3. In your functional test inject that piece of HTML representing the Custom Element
4. Adjust the URL in `Page Delivery` configuration to match the one used in your functional test
Also by running the functional test with`:watch` you can inspect the network tab and check the actual response and adjust the test.

This approach would work with any other functional test use case that involves a production VEC activity for Target.

cc: @jonsnyder @shammowla @jfkhoury

**Comment by XDex** [comment]
@ninaceban Thank you for detailing the workaround, I'll close this PR and follow it to create the functional test. I still have some reservations regarding this approach, as whenever we'll need to make any modification to test activities in Target UI or add new ones, we'll need to change the URL back to `localhost`, and run the test with a local http server prior to editing the activity, which is not ideal..

**Pull request closed without merging**
