### PR TITLE
Fix broken link to User Docs

### PR DESCRIPTION
**Pull request by littlebutty**
## Description

Just fixed a broken link to the user docs.

## Motivation and Context

Broken link

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Improvement (non-breaking change which does not add functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html) or I'm an Adobe employee.
- [ ] I have made any necessary test changes and all tests pass.
- [ ] I have run the Sandbox successfully.

### CODE REVIEW

**Review by ninaceban — APPROVED** [review]
Thank you 👍

**Review by jfkhoury — APPROVED** [review]
Thank you! @liljenback was going to update the adobe ly links but he's out today - should we wait or merge this one?

**Comment by carterworks** [comment]
I've created #815 to fix the other broken links in the source code.

**Comment by jonsnyder** [comment]
We should update the bitly link so that old versions of the SDK get the correct link.

**Pull request merged**
