### PR TITLE
Fix broken documentation links in code

### PR DESCRIPTION
**Pull request by carterworks**
## Description

I fixed 3 broken documentation links.

## Related Issue

#808 first made us aware of the issue.

#813 fixes the issue in the README, this fixes a few of the issues throughout the code, in error messages and comments.

## Motivation and Context

https://developer.adobe.com/apis/experience-platform was deprecated, which all our short links pointed to. The new home for Alloy user documentation is now at https://experienceleague.adobe.com/docs/experience-platform/edge/

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Improvement (non-breaking change which does not add functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html) or I'm an Adobe employee.
- [ ] I have made any necessary test changes and all tests pass.
- [ ] I have run the Sandbox successfully.

### CODE REVIEW

**Comment by carterworks** [comment]
It looks like the unit tests failed because of a SauceLabs thing (maybe rate limiting?), not because of any actual test failures.

**Review by jonsnyder — CHANGES_REQUESTED** [review]
The idea with the bitly links is that we can update the URLs without having to change the code. This is so that people with old versions of the SDK can follow these links and be redirected to the correct URL. We should update the bitly links to point to the correct place. Then a code change isn't necessary. We should do this with #813 as well. Maybe we could add some documentation to the GIT wiki on how to do this.

**Comment by carterworks** [comment]
I've talked with Martin, and I don't think we can just update the target of the shortlinks like that without changing the hash. To point to a new location, I'm 85% sure we need to change the link itself.

**Review by liljenback — APPROVED** [review]

**Review by jonsnyder — APPROVED** [review]
If we don't hear back from corporate on possibly redirecting the old links, I'm fine with changing these.

**Comment by jfkhoury** [comment]
@liljenback I thought there's a tool somewhere that allows updating those URL without changing them, is that not the case?

**Pull request merged**
